spring:
    main:
        banner-mode: "off"
    thymeleaf:
        cache: false
    jpa:
        spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
        hibernate.ddl-auto: update
    h2:
        console.enabled: true
        console.path: /h2
    datasource:
        url: jdbc:h2:file:C:/data/sample/test2 #(for Windows machine)
        # url: jdbc:h2:./data #(for Mac machine)
        username: sa
        password: password
        driver-class-name: org.h2.Driver
    flyway:
        enabled: false #disable flyway auto config in order to make it start after Hibernate created table schema

