spring:
    main:
        web-application-type: NONE
    thymeleaf:
        cache: false
    jpa:
        spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
        hibernate.ddl-auto: update
    h2:
        console.enabled: true
        console.path: /h2
    datasource:
        url: jdbc:h2:file:C:/data/sample #jdbc:h2:file:/data/sample (Windows only)
        username: sa
        password: password
        driver-class-name: org.h2.Driver
    flyway:
        baseline-on-migrate: true
        baselineVersion: 0.0

web:
    enabled: false

